---
title: "Untitled"
author: "Broncio Aguilar-Sanjuan"
date: "09/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Visualisation of proteins with R

Installation instructions for `NGLVieweR` available on the GitHub repo [here](https://github.com/nvelden/NGLVieweR)

```{r,}
library("NGLVieweR")
library("tidyverse")
```

Examples of use [here](https://nvelden.github.io/NGLVieweR/articles/NGLVieweR.html)


Fetch structure directly from the PDB provided a `pdb_id`
```{r,}
pdb_id <- "2pne"
NGLVieweR(pdb_id) %>% addRepresentation("cartoon")
```
Test further

```{r,}
NGLVieweR("7CID") %>%
  stageParameters(
    zoomSpeed=1
    ) %>%
  addRepresentation(
    "cartoon",
    param = list(name="cartoon", 
                 colorScheme="residueindex",
                 backgroundColor="white"
                 )
  ) %>%
setSpin()
```

```{r,}
NGLVieweR("7CID") %>%
 stageParameters(backgroundColor = "white", zoomSpeed = 1) %>%
 addRepresentation("cartoon", param = list(name = "cartoon", colorScheme="residueindex"))

if (interactive()) {
  library(shiny)
  ui <- fluidPage(NGLVieweROutput("structure"))
  server <- function(input, output) {
    output$structure <- renderNGLVieweR({
      NGLVieweR("7CID") %>%
        stageParameters(backgroundColor = "white", zoomSpeed = 1) %>%
        addRepresentation("cartoon",
          param = list(name = "cartoon", colorScheme = "residueindex")
        )
    })
  }
  shinyApp(ui, server)
}
```
## API

This launches a window for visualisation with basic GUI with user-defined action buttons.
It gives an option to launch the visualisation on the browser. 

```{r,}
library(shiny)
library(NGLVieweR)

ui <- fluidPage(
  titlePanel("Viewer with API inputs"),
  sidebarLayout(
    sidebarPanel(
      textInput("selection", "Selection", "1-20"),
      selectInput("type", "Type", c("ball+stick", "cartoon", "backbone")),
      selectInput("color", "Color", c("orange", "grey", "white")),
      actionButton("add", "Add"),
      actionButton("remove", "Remove")
    ),
    mainPanel(
      NGLVieweROutput("structure")
    )
  )
)
server <- function(input, output) {
  output$structure <- renderNGLVieweR({
    NGLVieweR("7CID") %>%
      addRepresentation("cartoon",
        param = list(name = "cartoon", colorScheme = "residueindex")
      ) %>%
      stageParameters(backgroundColor = input$backgroundColor) %>%
      setQuality("high") %>%
      setFocus(0) %>%
      setSpin(TRUE)
  })
  observeEvent(input$add, {
    NGLVieweR_proxy("structure") %>%
      addSelection(isolate(input$type),
        param =
          list(
            name = "sel1",
            sele = isolate(input$selection),
            colorValue = isolate(input$color)
          )
      )
  })
  observeEvent(input$remove, {
    NGLVieweR_proxy("structure") %>%
      removeSelection("sel1")
  })
}
shinyApp(ui, server)
```